import { initializeTestEnvironment, assertSucceeds, assertFails } from '@firebase/rules-unit-testing';
import fs from 'fs';
const env = await initializeTestEnvironment({ projectId:'demo-haras', firestore:{ host:'127.0.0.1', port:8085, rules: fs.readFileSync('proj/firestore.rules','utf8') } });
let ok=0, bad=0;
const t = async (nome, p, esperado)=>{ try{ await (esperado? assertSucceeds(p): assertFails(p)); ok++; console.log('OK  ', nome); }catch(e){ bad++; console.log('FALHA', nome, e.message.slice(0,80)); } };
const anon = env.unauthenticatedContext().firestore();
const orig = env.authenticatedContext('gustavo',{email:'g@x.com'}).firestore();           // sem claim = haras original
const a = env.authenticatedContext('ua',{tenantId:'cli-a'}).firestore();
const b = env.authenticatedContext('ub',{tenantId:'cli-b'}).firestore();
const vazio = env.authenticatedContext('uv',{tenantId:''}).firestore();
await env.withSecurityRulesDisabled(async c=>{ await c.firestore().doc('harasData/horses_list').set({value:[1]}); await c.firestore().doc('tenants/cli-a/dados/horses_list').set({value:[2]}); await c.firestore().doc('tenants/cli-b/dados/horses_list').set({value:[3]}); });
await t('anônimo NÃO lê harasData', anon.doc('harasData/horses_list').get(), false);
await t('anônimo NÃO grava harasData', anon.doc('harasData/horses_list').set({value:[]}), false);
await t('haras original LÊ harasData', orig.doc('harasData/horses_list').get(), true);
await t('haras original GRAVA harasData', orig.doc('harasData/horses_list').set({value:[1,2]}), true);
await t('haras original NÃO lê cliente A', orig.doc('tenants/cli-a/dados/horses_list').get(), false);
await t('haras original NÃO grava cliente A', orig.doc('tenants/cli-a/dados/horses_list').set({value:[]}), false);
await t('cliente A LÊ os próprios dados', a.doc('tenants/cli-a/dados/horses_list').get(), true);
await t('cliente A GRAVA os próprios dados', a.doc('tenants/cli-a/dados/horses_list').set({value:[9]}), true);
await t('cliente A NÃO lê cliente B', a.doc('tenants/cli-b/dados/horses_list').get(), false);
await t('cliente A NÃO grava cliente B', a.doc('tenants/cli-b/dados/horses_list').set({value:[]}), false);
await t('cliente A NÃO lê harasData (haras original)', a.doc('harasData/horses_list').get(), false);
await t('cliente A NÃO grava harasData', a.doc('harasData/horses_list').set({value:[]}), false);
await t('cliente A NÃO apaga harasData', a.doc('harasData/horses_list').delete(), false);
await t('cliente B LÊ o próprio', b.doc('tenants/cli-b/dados/horses_list').get(), true);
await t('claim vazia NÃO lê harasData', vazio.doc('harasData/horses_list').get(), false);
await t('outra coleção bloqueada (original)', orig.doc('qualquercoisa/x').get(), false);
await t('outra coleção bloqueada (cliente)', a.doc('usuarios/x').set({a:1}), false);
await t('listar coleção do cliente A (query)', a.collection('tenants/cli-a/dados').get(), true);
await t('cliente A NÃO lista coleção do B', a.collection('tenants/cli-b/dados').get(), false);
console.log(`\n${ok} passaram, ${bad} falharam`);
await env.cleanup(); process.exit(bad?1:0);
