import { initializeTestEnvironment, assertSucceeds, assertFails } from '@firebase/rules-unit-testing';
import fs from 'fs';
const env = await initializeTestEnvironment({ projectId:'demo-haras', firestore:{ host:'127.0.0.1', port:8085, rules: fs.readFileSync('proj/firestore.rules.2b','utf8') } });
let ok=0, bad=0;
const t = async (nome, p, esperado)=>{ try{ await (esperado? assertSucceeds(p): assertFails(p)); ok++; console.log('OK  ', nome); }catch(e){ bad++; console.log('FALHA', nome); } };
const adm = env.authenticatedContext('g',{papel:'admin',modulos:['financeiro']}).firestore();
const fun = env.authenticatedContext('f',{papel:'funcionario',modulos:['animais']}).firestore();
const semPapel = env.authenticatedContext('s',{}).firestore();
const ca = env.authenticatedContext('ca',{tenantId:'cli-a',papel:'admin'}).firestore();
const cf = env.authenticatedContext('cf',{tenantId:'cli-a',papel:'funcionario'}).firestore();
await env.withSecurityRulesDisabled(async c=>{ const d=c.firestore(); await d.doc('harasData/usuarios_list').set({value:[{admin:true}]}); await d.doc('harasData/horses_list').set({value:[1]}); await d.doc('tenants/cli-a/dados/usuarios_list').set({value:[]}); });
await t('admin GRAVA usuarios_list (original)', adm.doc('harasData/usuarios_list').set({value:[{admin:true},{x:1}]}), true);
await t('funcionário LÊ usuarios_list', fun.doc('harasData/usuarios_list').get(), true);
await t('funcionário NÃO grava usuarios_list (se promover a admin)', fun.doc('harasData/usuarios_list').set({value:[{admin:true,eu:1}]}), false);
await t('funcionário NÃO apaga usuarios_list', fun.doc('harasData/usuarios_list').delete(), false);
await t('sem papel NÃO grava usuarios_list', semPapel.doc('harasData/usuarios_list').set({value:[]}), false);
await t('funcionário GRAVA horses_list normalmente', fun.doc('harasData/horses_list').set({value:[1,2]}), true);
await t('funcionário GRAVA estoque normalmente', fun.doc('harasData/estoque_produtos').set({value:[]}), true);
await t('sem papel GRAVA horses_list (como hoje)', semPapel.doc('harasData/horses_list').set({value:[3]}), true);
await t('admin do cliente A grava usuarios_list do A', ca.doc('tenants/cli-a/dados/usuarios_list').set({value:[1]}), true);
await t('funcionário do cliente A NÃO grava usuarios_list do A', cf.doc('tenants/cli-a/dados/usuarios_list').set({value:[2]}), false);
await t('funcionário do cliente A grava horses do A', cf.doc('tenants/cli-a/dados/horses_list').set({value:[2]}), true);
await t('admin do cliente A NÃO grava usuarios_list do original', ca.doc('harasData/usuarios_list').set({value:[]}), false);
await t('admin do original NÃO grava no cliente A', adm.doc('tenants/cli-a/dados/horses_list').set({value:[]}), false);
await t('outra coleção bloqueada', adm.doc('x/y').get(), false);
console.log(`\n${ok} passaram, ${bad} falharam`); await env.cleanup(); process.exit(bad?1:0);
